# Generated by Django 5.0.14 on 2025-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.AutoField(db_column='BookID', primary_key=True, serialize=False)),
                ('isbn', models.CharField(db_column='ISBN', max_length=20, unique=True)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('genre', models.CharField(blank=True, db_column='Genre', max_length=100, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('author', models.CharField(db_column='Author', max_length=150)),
                ('price', models.DecimalField(db_column='Price', decimal_places=2, max_digits=10)),
                ('stoc', models.IntegerField(db_column='Stoc', default=0)),
            ],
            options={
                'db_table': 'Books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FirstName', max_length=100)),
                ('lastname', models.CharField(db_column='LastName', max_length=100)),
                ('email', models.CharField(db_column='Email', max_length=150, unique=True)),
                ('phone', models.CharField(db_column='Phone', max_length=20)),
                ('passwordhash', models.CharField(db_column='PasswordHash', max_length=256)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
